# Generated by Django 5.1 on 2024-08-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0003_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderYolzar',
        ),
    ]
