# Generated by Django 5.1 on 2024-08-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0004_rename_order_orderyolzar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderyolzar',
            table='orderY',
        ),
    ]
