# Generated by Django 5.1 on 2024-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0006_paypaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
