# Generated by Django 5.1 on 2024-08-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0007_cart_quantity_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
