# Generated by Django 5.1 on 2024-08-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0013_orderyolzar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderyolzar',
            name='user',
        ),
    ]
