# Generated by Django 5.1 on 2024-08-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0019_orderitem_price_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
